# https://beta.ruff.rs
# https://docs.pytest.org
name: test_python
on:
  push:
  #  branches: [master]
  pull_request:
    branches: [master]
jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install --user pytest ruff
    - run: ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
    # - run: ruff --format=github --line-length=200 --target-version=py37 .
    # - run: ruff --format=github --target-version=py37 .
    # Fix https://github.com/test262-utils/test262-harness-py/issues/8 and remove `|| true`
    - run: pytest --ignore=test/test_common.py --ignore=test/test_parseTestRecord.py
    - run: pytest || true
